In [65]:
5

5

In [66]:
3+2

5

In [67]:
5/3

1.6666666666666667

In [68]:
5*3

15

In [69]:
var1 = 50

In [70]:
var1

50

In [71]:
var1*5

250

In [72]:
var2 = 'haha'

In [73]:
var2

'haha'

In [74]:
var2*3

'hahahahahaha'

In [75]:
type(var2)

str

In [76]:
type(var1)

int

In [77]:
var3 = [1, 2, 3, 4, 5, 6]

In [78]:
var3

[1, 2, 3, 4, 5, 6]

In [79]:
var3[1]

2

In [80]:
var3[0]

1

In [81]:
var3*3

[1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6]

In [82]:
var3[-1]

6

In [83]:
var4 = [3, 4, 'a', 'b']

In [84]:
var4.append('c')

In [85]:
var4

[3, 4, 'a', 'b', 'c']

In [86]:
var4.insert(2, 6)

In [87]:
var4

[3, 4, 6, 'a', 'b', 'c']

In [88]:
var4[3]

'a'

In [89]:
import pandas as pd

In [90]:
TrSet = pd.read_csv('TrSet.csv')

In [91]:
TrSet

,CUST_NO,VTG,AGETIER,EDUCATION_DESC,GENDER,EOP_BAL_CS,MTH_AVG_BAL_CS,MTH6_AVG_BAL_CS,DELTA_FUNDING_BALANCE,MTH_AVG_BAL_IDR,...,AVG_CREDIT_3MTH,SUM_CREDIT_LESS_3MIL,SUM_CREDIT_ZERO,DELTA_CREDIT_MUTATION,DELTA_DEBIT_MUTATION,AVG_DEBIT_3MTH,CUST_SEGMENT_AVG,DELTA_CUST_SEG,L_COLL,BAD_TAG
0,2730505.6,16-20 th,21-30 th,UNIVERSITAS,P,2.056059e+07,1.984331e+07,8.539044e+06,-1.348543e+07,1.984331e+07,...,2.498304e+07,0,0,-1.623916e+07,-1.062066e+07,1.949566e+07,4,0,0,0
1,2734315.2,16-20 th,41-50 th,UNIVERSITAS,L,9.170948e+05,2.694370e+06,1.951391e+07,3.405224e+07,2.694370e+06,...,1.124538e+07,0,0,-6.775181e+06,-2.692690e+06,1.276439e+07,5,0,1,0
2,2668305.2,16-20 th,41-50 th,UNIVERSITAS,L,4.300652e+05,1.719333e+06,1.974608e+06,7.410419e+05,1.719333e+06,...,1.474981e+07,1,0,8.661768e+06,1.129421e+07,1.463569e+07,5,0,0,0
3,2526375.6,16-20 th,41-50 th,UNIVERSITAS,L,4.348930e+06,1.373424e+06,1.874303e+06,1.571728e+06,1.373424e+06,...,6.541202e+06,0,0,3.685779e+06,8.645953e+05,6.047069e+06,5,0,0,0
4,2437968.4,16-20 th,51-65 th,SMA,L,6.702202e+07,1.855625e+08,2.803859e+08,4.921136e+08,1.855625e+08,...,1.017353e+09,0,0,-2.065421e+08,7.833901e+08,1.034371e+09,3,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
43621,7749589.4,1 th,21-30 th,SMA,L,9.897000e+05,6.301286e+05,6.398094e+05,-5.737353e+04,6.301286e+05,...,3.631500e+06,1,0,-6.452000e+05,3.802667e+05,3.540033e+06,5,0,0,0
43622,7801324.8,1 th,31-40 th,AKADEMI,P,8.365746e+06,2.129412e+06,9.997117e+05,-8.284994e+05,2.129412e+06,...,2.065541e+07,1,1,-1.554145e+05,2.162427e+06,1.788757e+07,5,1,0,0
43623,7803506.8,1 th,21-30 th,UNIVERSITAS,L,2.424743e+07,1.738847e+07,7.323877e+06,-1.275150e+07,1.738847e+07,...,1.110606e+07,2,0,-9.906002e+06,-5.826008e+06,5.826008e+06,4,0,0,0
43624,4734476.0,6-10 th,31-40 th,SMA,L,1.670087e+07,7.784549e+06,8.533363e+06,1.212635e+06,7.784549e+06,...,1.201513e+08,0,0,-2.037767e+07,1.908234e+07,1.207426e+08,4,0,0,0
43625,3639642.0,11-15 th,51-65 th,SD,L,5.242412e+08,5.212897e+08,5.075936e+08,-2.307968e+07,6.212897e+08,...,3.977569e+06,2,0,-3.296693e+06,-3.493315e+06,3.578730e+06,2,0,0,0

In [92]:
TrSet.head()

,CUST_NO,VTG,AGETIER,EDUCATION_DESC,GENDER,EOP_BAL_CS,MTH_AVG_BAL_CS,MTH6_AVG_BAL_CS,DELTA_FUNDING_BALANCE,MTH_AVG_BAL_IDR,...,AVG_CREDIT_3MTH,SUM_CREDIT_LESS_3MIL,SUM_CREDIT_ZERO,DELTA_CREDIT_MUTATION,DELTA_DEBIT_MUTATION,AVG_DEBIT_3MTH,CUST_SEGMENT_AVG,DELTA_CUST_SEG,L_COLL,BAD_TAG
0,2730505.6,16-20 th,21-30 th,UNIVERSITAS,P,20560590.01,1.984331e+07,8.539044e+06,-1.348543e+07,1.984331e+07,...,2.498304e+07,0,0,-1.623916e+07,-1.062066e+07,1.949566e+07,4,0,0,0
1,2734315.2,16-20 th,41-50 th,UNIVERSITAS,L,917094.84,2.694370e+06,1.951391e+07,3.405224e+07,2.694370e+06,...,1.124538e+07,0,0,-6.775181e+06,-2.692690e+06,1.276439e+07,5,0,1,0
2,2668305.2,16-20 th,41-50 th,UNIVERSITAS,L,430065.24,1.719333e+06,1.974608e+06,7.410419e+05,1.719333e+06,...,1.474981e+07,1,0,8.661768e+06,1.129421e+07,1.463569e+07,5,0,0,0
3,2526375.6,16-20 th,41-50 th,UNIVERSITAS,L,4348929.80,1.373424e+06,1.874303e+06,1.571728e+06,1.373424e+06,...,6.541202e+06,0,0,3.685779e+06,8.645953e+05,6.047069e+06,5,0,0,0
4,2437968.4,16-20 th,51-65 th,SMA,L,67022018.69,1.855625e+08,2.803859e+08,4.921136e+08,1.855625e+08,...,1.017353e+09,0,0,-2.065421e+08,7.833901e+08,1.034371e+09,3,0,0,0

In [93]:
TrSet[['CUST_NO', 'VTG']].head()

     CUST_NO       VTG
0  2730505.6  16-20 th
1  2734315.2  16-20 th
2  2668305.2  16-20 th
3  2526375.6  16-20 th
4  2437968.4  16-20 th

In [94]:
TrSet.iloc[2, 0]

np.float64(2668305.2)

In [95]:
TrSet.iloc[1:5, 1:3]

        VTG   AGETIER
1  16-20 th  41-50 th
2  16-20 th  41-50 th
3  16-20 th  41-50 th
4  16-20 th  51-65 th

In [96]:
TrSet.iloc[:, 2:4]

        AGETIER EDUCATION_DESC
0      21-30 th    UNIVERSITAS
1      41-50 th    UNIVERSITAS
2      41-50 th    UNIVERSITAS
3      41-50 th    UNIVERSITAS
4      51-65 th            SMA
...         ...            ...
43621  21-30 th            SMA
43622  31-40 th        AKADEMI
43623  21-30 th    UNIVERSITAS
43624  31-40 th            SMA
43625  51-65 th             SD

[43626 rows x 2 columns]

In [97]:
dfCustNo = TrSet[['CUST_NO']]

In [98]:
dfCustNo.head()

     CUST_NO
0  2730505.6
1  2734315.2
2  2668305.2
3  2526375.6
4  2437968.4

In [99]:
TrSet.head()

,CUST_NO,VTG,AGETIER,EDUCATION_DESC,GENDER,EOP_BAL_CS,MTH_AVG_BAL_CS,MTH6_AVG_BAL_CS,DELTA_FUNDING_BALANCE,MTH_AVG_BAL_IDR,...,AVG_CREDIT_3MTH,SUM_CREDIT_LESS_3MIL,SUM_CREDIT_ZERO,DELTA_CREDIT_MUTATION,DELTA_DEBIT_MUTATION,AVG_DEBIT_3MTH,CUST_SEGMENT_AVG,DELTA_CUST_SEG,L_COLL,BAD_TAG
0,2730505.6,16-20 th,21-30 th,UNIVERSITAS,P,20560590.01,1.984331e+07,8.539044e+06,-1.348543e+07,1.984331e+07,...,2.498304e+07,0,0,-1.623916e+07,-1.062066e+07,1.949566e+07,4,0,0,0
1,2734315.2,16-20 th,41-50 th,UNIVERSITAS,L,917094.84,2.694370e+06,1.951391e+07,3.405224e+07,2.694370e+06,...,1.124538e+07,0,0,-6.775181e+06,-2.692690e+06,1.276439e+07,5,0,1,0
2,2668305.2,16-20 th,41-50 th,UNIVERSITAS,L,430065.24,1.719333e+06,1.974608e+06,7.410419e+05,1.719333e+06,...,1.474981e+07,1,0,8.661768e+06,1.129421e+07,1.463569e+07,5,0,0,0
3,2526375.6,16-20 th,41-50 th,UNIVERSITAS,L,4348929.80,1.373424e+06,1.874303e+06,1.571728e+06,1.373424e+06,...,6.541202e+06,0,0,3.685779e+06,8.645953e+05,6.047069e+06,5,0,0,0
4,2437968.4,16-20 th,51-65 th,SMA,L,67022018.69,1.855625e+08,2.803859e+08,4.921136e+08,1.855625e+08,...,1.017353e+09,0,0,-2.065421e+08,7.833901e+08,1.034371e+09,3,0,0,0

In [100]:
TrSet = TrSet.drop(['CUST_NO'], axis=1)

In [101]:
TrSet.head()

,VTG,AGETIER,EDUCATION_DESC,GENDER,EOP_BAL_CS,MTH_AVG_BAL_CS,MTH6_AVG_BAL_CS,DELTA_FUNDING_BALANCE,MTH_AVG_BAL_IDR,MTH6_AVG_BAL_IDR,...,AVG_CREDIT_3MTH,SUM_CREDIT_LESS_3MIL,SUM_CREDIT_ZERO,DELTA_CREDIT_MUTATION,DELTA_DEBIT_MUTATION,AVG_DEBIT_3MTH,CUST_SEGMENT_AVG,DELTA_CUST_SEG,L_COLL,BAD_TAG
0,16-20 th,21-30 th,UNIVERSITAS,P,20560590.01,1.984331e+07,8.539044e+06,-1.348543e+07,1.984331e+07,8.539044e+06,...,2.498304e+07,0,0,-1.623916e+07,-1.062066e+07,1.949566e+07,4,0,0,0
1,16-20 th,41-50 th,UNIVERSITAS,L,917094.84,2.694370e+06,1.951391e+07,3.405224e+07,2.694370e+06,1.951391e+07,...,1.124538e+07,0,0,-6.775181e+06,-2.692690e+06,1.276439e+07,5,0,1,0
2,16-20 th,41-50 th,UNIVERSITAS,L,430065.24,1.719333e+06,1.974608e+06,7.410419e+05,1.719333e+06,1.974608e+06,...,1.474981e+07,1,0,8.661768e+06,1.129421e+07,1.463569e+07,5,0,0,0
3,16-20 th,41-50 th,UNIVERSITAS,L,4348929.80,1.373424e+06,1.874303e+06,1.571728e+06,1.373424e+06,1.874303e+06,...,6.541202e+06,0,0,3.685779e+06,8.645953e+05,6.047069e+06,5,0,0,0
4,16-20 th,51-65 th,SMA,L,67022018.69,1.855625e+08,2.803859e+08,4.921136e+08,1.855625e+08,2.803859e+08,...,1.017353e+09,0,0,-2.065421e+08,7.833901e+08,1.034371e+09,3,0,0,0

In [102]:
TrSet = pd.merge(dfCustNo, TrSet, how='left', left_index=True, right_index=True)

In [103]:
TrSet.head()

,CUST_NO,VTG,AGETIER,EDUCATION_DESC,GENDER,EOP_BAL_CS,MTH_AVG_BAL_CS,MTH6_AVG_BAL_CS,DELTA_FUNDING_BALANCE,MTH_AVG_BAL_IDR,...,AVG_CREDIT_3MTH,SUM_CREDIT_LESS_3MIL,SUM_CREDIT_ZERO,DELTA_CREDIT_MUTATION,DELTA_DEBIT_MUTATION,AVG_DEBIT_3MTH,CUST_SEGMENT_AVG,DELTA_CUST_SEG,L_COLL,BAD_TAG
0,2730505.6,16-20 th,21-30 th,UNIVERSITAS,P,20560590.01,1.984331e+07,8.539044e+06,-1.348543e+07,1.984331e+07,...,2.498304e+07,0,0,-1.623916e+07,-1.062066e+07,1.949566e+07,4,0,0,0
1,2734315.2,16-20 th,41-50 th,UNIVERSITAS,L,917094.84,2.694370e+06,1.951391e+07,3.405224e+07,2.694370e+06,...,1.124538e+07,0,0,-6.775181e+06,-2.692690e+06,1.276439e+07,5,0,1,0
2,2668305.2,16-20 th,41-50 th,UNIVERSITAS,L,430065.24,1.719333e+06,1.974608e+06,7.410419e+05,1.719333e+06,...,1.474981e+07,1,0,8.661768e+06,1.129421e+07,1.463569e+07,5,0,0,0
3,2526375.6,16-20 th,41-50 th,UNIVERSITAS,L,4348929.80,1.373424e+06,1.874303e+06,1.571728e+06,1.373424e+06,...,6.541202e+06,0,0,3.685779e+06,8.645953e+05,6.047069e+06,5,0,0,0
4,2437968.4,16-20 th,51-65 th,SMA,L,67022018.69,1.855625e+08,2.803859e+08,4.921136e+08,1.855625e+08,...,1.017353e+09,0,0,-2.065421e+08,7.833901e+08,1.034371e+09,3,0,0,0